const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
  return [
    C3.Plugins.Sprite,
    C3.Behaviors.solid,
    C3.Behaviors.Sin,
    C3.Behaviors.Tween,
    C3.Behaviors.Rotate,
    C3.Plugins.Spritefont2,
    C3.Plugins.Touch,
    C3.Plugins.LocalStorage,
    C3.Plugins.Audio,
    C3.Behaviors.Physics,
    C3.Plugins.Mouse,
    C3.Plugins.Particles,
    C3.Behaviors.Pin,
    C3.Behaviors.Timer,
    C3.Behaviors.DragnDrop,
    C3.Plugins.advert,
    C3.Plugins.PlatformInfo,
    C3.Plugins.TiledBg,
    C3.Plugins.System.Cnds.CompareVar,
    C3.Plugins.Audio.Acts.Play,
    C3.Plugins.System.Cnds.OnLayoutStart,
    C3.Plugins.System.Acts.SetLayerVisible,
    C3.Plugins.Audio.Acts.Stop,
    C3.Plugins.Audio.Acts.StopAll,
    C3.Plugins.Touch.Cnds.OnTouchEnd,
    C3.Plugins.Sprite.Acts.SetAnimFrame,
    C3.Plugins.System.Cnds.IsGroupActive,
    C3.Plugins.Touch.Cnds.IsTouchingObject,
    C3.Plugins.System.Cnds.LayerVisible,
    C3.Plugins.System.Acts.Wait,
    C3.Plugins.System.Acts.SetVar,
    C3.Plugins.LocalStorage.Acts.SetItem,
    C3.Plugins.System.Acts.GoToLayout,
    C3.Plugins.System.Acts.RestartLayout,
    C3.Plugins.Spritefont2.Acts.SetText,
    C3.Plugins.Sprite.Acts.SetOpacity,
    C3.Plugins.Sprite.Acts.SetPos,
    C3.Plugins.Touch.Exps.X,
    C3.Plugins.Touch.Cnds.IsInTouch,
    C3.Plugins.Sprite.Exps.Y,
    C3.Behaviors.DragnDrop.Cnds.IsDragging,
    C3.Plugins.Sprite.Exps.X,
    C3.Plugins.Sprite.Exps.Width,
    C3.Plugins.System.Exps.layoutwidth,
    C3.Behaviors.Pin.Acts.PinByProperties,
    C3.Plugins.System.Cnds.Every,
    C3.Plugins.System.Acts.AddVar,
    C3.Plugins.Sprite.Cnds.IsOverlapping,
    C3.Plugins.System.Cnds.Compare,
    C3.Plugins.System.Acts.CreateObject,
    C3.Plugins.Sprite.Acts.SetAnim,
    C3.Plugins.Sprite.Acts.SetInstanceVar,
    C3.Behaviors.Physics.Acts.SetWorldGravity,
    C3.Plugins.Sprite.Acts.Destroy,
    C3.Plugins.System.Acts.CreateObjectByName,
    C3.Plugins.System.Exps.layoutheight,
    C3.Plugins.Sprite.Acts.SetScale,
    C3.Behaviors.Tween.Acts.TweenTwoProperties,
    C3.Behaviors.Tween.Acts.TweenOneProperty,
    C3.Plugins.Sprite.Acts.MoveToBottom,
    C3.Plugins.System.Exps.choose,
    C3.Plugins.System.Cnds.ForEach,
    C3.Plugins.Sprite.Cnds.OnCollision,
    C3.Plugins.Sprite.Exps.UID,
    C3.Plugins.Sprite.Exps.AnimationName,
    C3.Plugins.Sprite.Acts.AddInstanceVar,
    C3.Plugins.Particles.Acts.SetPos,
    C3.Plugins.Sprite.Acts.Spawn,
    C3.Plugins.Spritefont2.Acts.SetPos,
    C3.Plugins.Spritefont2.Exps.Width,
    C3.Plugins.Spritefont2.Exps.Height,
    C3.Plugins.Spritefont2.Exps.X,
    C3.Plugins.Spritefont2.Exps.Y,
    C3.Plugins.Spritefont2.Acts.MoveToTop,
    C3.Behaviors.Timer.Acts.StartTimer,
    C3.Behaviors.Timer.Acts.PauseResumeTimer,
    C3.Behaviors.Timer.Cnds.IsTimerRunning,
    C3.Behaviors.Physics.Acts.SetEnabled,
    C3.Behaviors.DragnDrop.Acts.SetEnabled,
    C3.Plugins.System.Cnds.For,
    C3.Plugins.Sprite.Exps.PickedCount,
    C3.Plugins.Sprite.Cnds.PickDistance,
    C3.Plugins.Sprite.Acts.SetVisible,
    C3.Plugins.System.Cnds.Else,
    C3.Plugins.LocalStorage.Acts.CheckItemExists,
    C3.Plugins.LocalStorage.Cnds.OnItemExists,
    C3.Plugins.LocalStorage.Acts.GetItem,
    C3.Plugins.LocalStorage.Cnds.OnItemGet,
    C3.Plugins.LocalStorage.Exps.ItemValue,
  ];
};
self.C3_JsPropNameTable = [
  { Solid: 0 },
  { button_startgame: 0 },
  { icon_crown: 0 },
  { start_logo: 0 },
  { Sine: 0 },
  { Tween: 0 },
  { start_fruitbubble_: 0 },
  { start_fruitbubble_2: 0 },
  { start_fruitbubble_3: 0 },
  { Sine2: 0 },
  { start_fruitbubble_4: 0 },
  { start_fruitbubble_5: 0 },
  { start_fruitbubble_6: 0 },
  { panel_bg_dark: 0 },
  { panel_bg: 0 },
  { panel_button_close: 0 },
  { panel_button_sound_: 0 },
  { panel_button_music_: 0 },
  { panel_button_home: 0 },
  { panel_button_retry: 0 },
  { howtoplay: 0 },
  { Rotate: 0 },
  { gameover_light: 0 },
  { gameover_panelbg: 0 },
  { gameover_button_home: 0 },
  { gameover_button_retry: 0 },
  { ingame_button_options: 0 },
  { ingamescore: 0 },
  { title_howtoplay: 0 },
  { title_gameover: 0 },
  { gameover_score: 0 },
  { gameover_score_desc: 0 },
  { title_options: 0 },
  { Touch: 0 },
  { bestscore: 0 },
  { ingame_button_info: 0 },
  { Loading_Progresse_Text: 0 },
  { LocalStorage: 0 },
  { Audio: 0 },
  { Physics: 0 },
  { wall: 0 },
  { Mouse: 0 },
  { Particles_outline: 0 },
  { Particles: 0 },
  { Particles_outline2: 0 },
  { next: 0 },
  { ingame_next_: 0 },
  { Pin: 0 },
  { drop_fruit: 0 },
  { drop_line: 0 },
  { home_bestscore: 0 },
  { Timer: 0 },
  { dotted_line: 0 },
  { level: 0 },
  { Sprite: 0 },
  { DragDrop: 0 },
  { dragdrop: 0 },
  { MobileAdvert: 0 },
  { PlatformInfo: 0 },
  { game_bg2: 0 },
  { dot: 0 },
  { clickarea: 0 },
  { explosion_score: 0 },
  { TiledBackground: 0 },
  { errorline: 0 },
  { SpritesB: 0 },
  { SpritesA: 0 },
  { sound: 0 },
  { music: 0 },
  { now: 0 },
  { deadline: 0 },
  { dropfriuttime: 0 },
  { loadingbar: 0 },
];

self.InstanceType = {
  button_startgame: class extends self.ISpriteInstance {},
  icon_crown: class extends self.ISpriteInstance {},
  start_logo: class extends self.ISpriteInstance {},
  start_fruitbubble_: class extends self.ISpriteInstance {},
  start_fruitbubble_2: class extends self.ISpriteInstance {},
  start_fruitbubble_3: class extends self.ISpriteInstance {},
  start_fruitbubble_4: class extends self.ISpriteInstance {},
  start_fruitbubble_5: class extends self.ISpriteInstance {},
  start_fruitbubble_6: class extends self.ISpriteInstance {},
  panel_bg_dark: class extends self.ISpriteInstance {},
  panel_bg: class extends self.ISpriteInstance {},
  panel_button_close: class extends self.ISpriteInstance {},
  panel_button_sound_: class extends self.ISpriteInstance {},
  panel_button_music_: class extends self.ISpriteInstance {},
  panel_button_home: class extends self.ISpriteInstance {},
  panel_button_retry: class extends self.ISpriteInstance {},
  howtoplay: class extends self.ISpriteInstance {},
  gameover_light: class extends self.ISpriteInstance {},
  gameover_panelbg: class extends self.ISpriteInstance {},
  gameover_button_home: class extends self.ISpriteInstance {},
  gameover_button_retry: class extends self.ISpriteInstance {},
  ingame_button_options: class extends self.ISpriteInstance {},
  ingamescore: class extends self.ISpriteFontInstance {},
  title_howtoplay: class extends self.ISpriteFontInstance {},
  title_gameover: class extends self.ISpriteFontInstance {},
  gameover_score: class extends self.ISpriteFontInstance {},
  gameover_score_desc: class extends self.ISpriteFontInstance {},
  title_options: class extends self.ISpriteFontInstance {},
  Touch: class extends self.IInstance {},
  bestscore: class extends self.ISpriteFontInstance {},
  ingame_button_info: class extends self.ISpriteInstance {},
  Loading_Progresse_Text: class extends self.ISpriteFontInstance {},
  LocalStorage: class extends self.IInstance {},
  Audio: class extends self.IInstance {},
  wall: class extends self.ISpriteInstance {},
  Mouse: class extends self.IInstance {},
  Particles_outline: class extends self.IParticlesInstance {},
  Particles: class extends self.IParticlesInstance {},
  Particles_outline2: class extends self.IParticlesInstance {},
  next: class extends self.ISpriteFontInstance {},
  ingame_next_: class extends self.ISpriteInstance {},
  drop_fruit: class extends self.ISpriteInstance {},
  drop_line: class extends self.ISpriteInstance {},
  home_bestscore: class extends self.ISpriteFontInstance {},
  dotted_line: class extends self.ISpriteInstance {},
  Sprite: class extends self.ISpriteInstance {},
  dragdrop: class extends self.ISpriteInstance {},
  MobileAdvert: class extends self.IInstance {},
  PlatformInfo: class extends self.IInstance {},
  game_bg2: class extends self.ISpriteInstance {},
  dot: class extends self.ISpriteInstance {},
  clickarea: class extends self.ISpriteInstance {},
  explosion_score: class extends self.ISpriteFontInstance {},
  TiledBackground: class extends self.ITiledBackgroundInstance {},
  errorline: class extends self.ISpriteInstance {},
  SpritesB: class extends self.ISpriteInstance {},
  SpritesA: class extends self.ISpriteInstance {},
};
